
package proxy;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ReleveService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReleveService {


    /**
     * 
     * @param rib
     * @return
     *     returns proxy.Releve
     */
    @WebMethod(operationName = "ConsulerRelever")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConsulerRelever", targetNamespace = "http://ws/", className = "proxy.ConsulerRelever")
    @ResponseWrapper(localName = "ConsulerReleverResponse", targetNamespace = "http://ws/", className = "proxy.ConsulerReleverResponse")
    @Action(input = "http://ws/ReleveService/ConsulerReleverRequest", output = "http://ws/ReleveService/ConsulerReleverResponse")
    public Releve consulerRelever(
        @WebParam(name = "rib", targetNamespace = "")
        String rib);

}
